version: '3'

services:
#  db:
#    image: postgres
  web:
    build: .
    command: >
      bash -c "sh init_conda.sh && sh start_django.sh"
    volumes:
      - ~/solida-core/projects:/root/projects
      - ~/solida-core/.tmp:/root/.tmp
      - ~/solida-core/profiles:/root/.local/share/solida/
      - .:/kode
      - ~/.ssh:/root/.ssh:ro

    ports:
      - "8000:8000"
#    depends_on:
#      - db

